name: Run OSS Chatbot

on:
  workflow_dispatch:  # you can trigger it manually from GitHub Actions tab
  push:
    branches:
      - main

jobs:
  run-chatbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Chatbot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python chatbot.py
